<?php
/**
 * Helpers functions
 *
 * @package Posts Extended
 */

/**
 * Display the posts.
 *
 * @param array $args User input.
 * @return mixed
 */
function rposts_get_posts( $args = array() ) {

	// Merge the input arguments and the defaults.
	$defs = rposts_get_defaults();
	$args = wp_parse_args( $args, $defs );

	// print_r( $args['container'] );

	// Set up a default, empty variable.
	$html = '';

	// Get the posts query.
	$posts = rposts_get_query( $args );

	if ( $posts->have_posts() ) :

		// Container open
		// Filters the list of HTML tags that are valid for use as list containers.
		$allowed_container_tags = apply_filters( 'rpost_container_allowedtags', array( 'div', 'section', 'aside' ) );
		if ( is_string( $args['container'] ) && in_array( $args['container'], $allowed_container_tags, true ) ) {
			$class = $args['container_class'] ? ' class="rposts ' . esc_attr( $args['container_class'] ) . '"' : ' class="rposts"';
			$id    = $args['container_id'] ? ' id="' . esc_attr( $args['container_id'] ) . '"' : '';
			$html .= '<' . esc_attr( $args['container'] ) . $id . $class . '>';
		}

		// Title.
		if ( $args['title'] ) {
			// Filters the list of HTML tags that are valid for use as title tags.
			$allowed_title_tags = apply_filters( 'rposts_title_allowedtags', array( 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'span', 'div' ) );
			if ( is_string( $args['title_tag'] ) && in_array( $args['title_tag'], $allowed_title_tags, true ) ) {
				$class = $args['title_class'] ? ' class="rposts__title ' . esc_attr( $args['title_class'] ) . '"' : ' class="rposts__title"';
				$html .= '<' . esc_attr( $args['title_tag'] ) . $class . '>';

				if ( $args['title_url'] ) {
					$html .= '<a href="' . esc_url( $args['title_url'] ) . '">' . esc_attr( $args['title'] ) . '</a>';
				} else {
					$html .= esc_attr( $args['title'] );
				}

				$html .= '</' . esc_attr( $args['title_tag'] ) . '>';
			}
		}

		// Loop through the query.
		while ( $posts->have_posts() ) :
			$posts->the_post();

			$html .= '<p>' . get_the_title() . '</p>';

		endwhile;

		// Container close.
		if ( is_string( $args['container'] ) && in_array( $args['container'], $allowed_container_tags, true ) ) {
			$html .= '</' . esc_attr( $args['container'] ) . '><!-- Generated by http://wordpress.org/plugins/recent-posts-widget-extended/ -->';
		}

	endif;

	// Restore original Post Data.
	wp_reset_postdata();

	return $html;
}
